backend:
  name: git-gateway
  branch: master
publish_mode: editorial_workflow

media_folder: "/assets/data"
public_folder: "/assets/data"

collections:
  - name: "project"
    label: "Project"
    folder: "assets/data/projects"
    media_folder: ""
    public_folder: ""
    create: true
    slug: "project_{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Dates", name: "dates", widget: "string"}
      - {label: "Collaborators", name: "collaborators", widget: "string", required: false}
      - {label: "CardDescription", name: "cardDescription", widget: "string"}
      - {label: "PreviewDesctiption", name: "previewDescription", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "hidden", default: "project"}
      - {label: "Layout", name: "layout", widget: "hidden", default: "project.njk"}


