backend:
  name: git-gateway
  branch: master
#publish_mode: editorial_workflow

media_folder: "public/assets/data"
public_folder: "/assets/data"

collections:
  - name: "project"
    label: "Project"
    folder: "src/projects"
    create: true
    slug: "project-{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Year", name: "year", widget: "string"}
      - {label: "Link to original material", name: "link", widget: "string", required: false}
      - {label: "Collaborators", name: "collaborators", widget: "string", required: false}
      - {label: "Thumbnail description", name: "thumbnailDescription", widget: "string"}
      - {label: "Preview summary", name: "summary", widget: "string"}
      - {label: "Content", name: "content", widget: "markdown"}
      - label: "Related projects"
        name: "relatedProjects"
        widget: "list"
        min: 1
        max: 3
        fields:
          - {label: "Project", name: "project", widget: "relation", collection: "project", value_field: "title"}
  - name: "publication"
      label: "Publication"
      folder: "src/publications"
      create: true
      slug: "publication-{{slug}}"
      fields:
        - {label: "Title", name: "title", widget: "string"}
        - {label: "Year", name: "year", widget: "string"}
        - {label: "ISBN", name: "isbn", widget: "string"}
        - {label: "Thumbnail description", name: "description", widget: "string"}
        - {label: "Link to publication", name: "link", widget: "string", required: false}
  - name: "news"
    label: "News"
    folder: "src/news"
    create: true
    slug: "news-{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Thumbnail description", name: "description", widget: "string"}
      - {label: "Link to publication", name: "link", widget: "string", required: false}

