backend:
  name: git-gateway
  branch: master

media_folder: "/assets/data"
public_folder: "/assets/data"

collections:
  - name: project
    label: Project
    folder: assets/data/projects/project
    media_folder: ""
    public_folder: ""
    create: true
    slug: "project_{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Dates", name: "dates", widget: "string"}
      - {label: "Collaborators", name: "collaborators", widget: "string", required: false}
      - {label: "CardDescription", name: "cardDescription", widget: "string"}
      - {label: "PreviewDesctiption", name: "previewDescription", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "hidden", default: "project"}
      - {label: "Layout", name: "layout", widget: "hidden", default: "project.njk"}
  - label: "Blog in English"
    name: "english_posts"
    folder: "_posts"
    create: true
    filter: {field: "language", value: "en"}
    fields:
      - {label: "Language", name: "language", widget: "select", options: ["en", "es"]}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Content", name: "body", widget: "markdown"}
  - label: "Blog en Español"
    name: "spanish_posts"
    folder: "_posts"
    create: true
    filter: {field: "language", value: "es"}
    fields:
      - {label: "Lenguaje", name: "language", widget: "select", options: ["en", "es"]}
      - {label: "Titulo", name: "title", widget: "string"}
      - {label: "Contenido", name: "body", widget: "markdown"}